### ISSUE TITLE
support for REFEDS hide-from-discovery

### ISSUE THREAD

**Issue by peter-** [leifj/pyFF#48]
Entities carrying the `http://macedir.org/entity-category` entity attibute with the  `http://refeds.org/category/hide-from-discovery` attribute value should not be shown in pyFF's DS.
(At least not unless some other UI element is added to allow subjects to also see any hidden entities, which would probably add too much noise to the UI.)

**Comment by leifj** [comment]
I believe this is now fully implemented.
