### ISSUE TITLE
Feature request: get all the entityID stored in pyff's repository

### ISSUE THREAD

**Issue by sitya** [leifj/pyFF#53]
It would be usefull to be able to get all the entityID stored in pyff's repository in json format. Like /entities gives the signed xml contains all entites, /entities.json would give a simple json array:
`{
"https://entity.id.1.com/idp",
"https://entity.id.2.com/idp",
"etc..."
}`

**Comment by leifj** [comment]
Hey @sitya - does it matter if the JSON contains more info than the entityIDs? Currently the discojson transform (as used for instance in examples/mdx.fd) results in a list of objects (one for each entity in the selection) where one of the fields is an entityID. Transforming this into what you are looking for is simply a matter of a python oneliner:

```python
#!/usr/bin/env python
import json
import sys

print json.dumps([e['entityID'] for e in json.load(sys.stdin)])
```

**Comment by sitya** [comment]
It works fine, thanks!

**Comment by leifj** [comment]
OK, lets close this issue then.
