### ISSUE TITLE
Certificate from SoftHSM missing from signed metadata

### ISSUE THREAD

**Issue by peter-** [leifj/pyFF#63]
Possibly more of a `pyXMLSecurity` issue, but I'll start here: When a certificate object accessed via PKCS11 is not publicly available (i.e., `pkcs11-tool -O` does not show it without logging in at the same time) `pyFF` does not include the certificate in the signed XML. While this is technically valid this makes it hard(er) to verify such signatures since the key used to sign is unkown.
In the case of SoftHSM this is possibly a configuration error (or environmental, due to use of old software, I've only tried Debian 7 or CentOS 6 so far) but I've failed to change the "private" attribute on the cert object and would therefore appreciate a workaround on the PKCS11 client side, e.g. getting the certificate object while we still have a session via PKCS11 during signing.
 
The problem can be experienced with the (immensly helpful!) files `p11setup.sh` and `p11.fd` from pyFF's `examples` directory, but to make this easier I've created a minimal self-contained testcase over at https://github.com/peter-/pyff-issue63-testcase

**Comment by leifj** [comment]
I think I have an idea - running regression tests now

**Comment by leifj** [comment]
Seems resolved now.
