### ISSUE TITLE
generated metadata validity timestamp misses "Z" timezone suffix

### ISSUE THREAD

**Issue by restena-sw** [leifj/pyFF#69]
I am executing

# TZ=UTC ./pyff --loglevel=INFO ../etc/edugain-sp.fd

and get a resulting file with

validUntil="2015-10-18T05:58:27.063864"

but the software consuming this dataset complains that there needs to be a trailing "Z" to indicate UTC time zone.

Other users of pyFF seem to get the timezone info. Maybe it's just something about my python environment (in which case it would be worth documenting it in pyFF's installation instructions). I have python 2.7.8 on openSUSE 13.2.

**Comment by leifj** [comment]
On 2015-09-18 08:11, restena-sw wrote:
> I am executing
> 
> 
>   TZ=UTC ./pyff --loglevel=INFO ../etc/edugain-sp.fd
> 
> and get a resulting file with
> 
> validUntil="2015-10-18T05:58:27.063864"
> 
> but the software consuming this dataset complains that there needs to be
> a trailing "Z" to indicate UTC time zone.
> 
> Other users of pyFF seem to get the timezone info. Maybe it's just
> something about my python environment (in which case it would be worth
> documenting it in pyFF's installation instructions). I have python 2.7.8
> on openSUSE 13.2.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/leifj/pyFF/issues/69>.
> 

This sounds like an old issue. Are you sure you are using the newest
version from github?

**Comment by restena-sw** [comment]
This is 0.9.4; updated with pip just this morning.

Too old?

Am 18.09.2015 um 11:16 schrieb Leif Johansson:
> On 2015-09-18 08:11, restena-sw wrote:
>> I am executing
>>
>>
>> TZ=UTC ./pyff --loglevel=INFO ../etc/edugain-sp.fd
>>
>> and get a resulting file with
>>
>> validUntil="2015-10-18T05:58:27.063864"
>>
>> but the software consuming this dataset complains that there needs to be
>> a trailing "Z" to indicate UTC time zone.
>>
>> Other users of pyFF seem to get the timezone info. Maybe it's just
>> something about my python environment (in which case it would be worth
>> documenting it in pyFF's installation instructions). I have python 2.7.8
>> on openSUSE 13.2.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/leifj/pyFF/issues/69>.
>>
> 
> This sounds like an old issue. Are you sure you are using the newest
> version from github?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/leifj/pyFF/issues/69#issuecomment-141390352>.
> 


-- 
Stefan WINTER
Ingenieur de Recherche
Fondation RESTENA - Réseau Téléinformatique de l'Education Nationale et
de la Recherche
6, rue Richard Coudenhove-Kalergi
L-1359 Luxembourg

Tel: +352 424409 1
Fax: +352 422473

PGP key updated to 4096 Bit RSA - I will encrypt all mails if the
recipient's key is known to me

http://pgp.mit.edu:11371/pks/lookup?op=get&search=0xC0DE6A358A39DC66

**Comment by restena-sw** [comment]
0.9.4 builtins.py line 888 an following state:

if offset is not None:
            dt = datetime.now() + offset
            e.set('validUntil', dt.isoformat())

but the .isoformat() function does NOT add a "Z" in the end. I believe this is where my problem comes from. Changing this if statement to an explicit strformat like a few lines up (massaging of the "ID" element) like this:

if offset is not None:
            dt = datetime.now() + offset
            e.set('validUntil', dt.strftime("%Y-%m-%dT%H:%M:%SZ"))

fixes the issues and sets the Z as it should.

I believe using isoformat() is a bug at this place and look forward to a fixed 0.9.5 :-)

**Comment by leifj** [comment]
can you verify this is a problem on HEAD (and perhaps provide a PR to fix it :-))

**Comment by restena-sw** [comment]
From reading master branch sources, it looks like this is indeed fixed there.
