### ISSUE TITLE
entitydescriptor tag cleanup

### ISSUE THREAD

**Issue by lhoekenga** [leifj/pyFF#77]
If pyff is used to build an aggregate file out of multiple small files containing single entityDescriptor elements, it seems new entityDescriptor open tags appear on the same line as the preceding entityDescriptor close tag, e.g.:

`</md:EntityDescriptor><md:EntityDescriptor entityID="https://example.edu/shibboleth">`

If pyff includes files with multiple entityDescriptor elements, it seems to put open tags on new lines, e.g.

    </md:EntityDescriptor>
    <md:EntityDescriptor entityID="https://example.edu/shibboleth">

I would like to see all entityDescriptor open tags appear on a new line.  Perhaps a change to tidy.xml?

**Comment by kevinfoote** [comment]
I believe you can use multiple xsl files so you can include the pretty-print (pp.xsl) as well as tidy  :)
(I'm not 100% on the syntax of this yet though)

```yaml
- xslt:
    stylesheet: tidy.xsl
- xslt: 
    stylesheet: pp.xsl
```

**Comment by leifj** [comment]
nothing is stopping you from doing multiple xslt pipes in a row like that today

**Comment by lhoekenga** [comment]
I didn't see the pretty print stylesheet.  Kevin pointed it out.  I apologize for the spurious request!
