### ISSUE TITLE
it should be possible to remove empty elements at the validation stage

### ISSUE THREAD

**Issue by kevinfoote** [leifj/pyFF#78]
Example incoming MD contains

```xml
<NameIDFormat>
  </NameIDFormat>
```

This is technically valid according to [1] uri standards.
However, this causes a SAML entity to choke on consumption - namely shibboleth-sp. 

[1] https://lists.w3.org/Archives/Public/xml-dist-app/2003Mar/0076.html

**Comment by kevinfoote** [comment]
Additional notes here this is what shib-sp is choking on .. which it turns out is not an empty string.
This passes tidy.xsl BTW... (is it supposed to?)

```xml
      <md:NameIDFormat>urn:mace:shibboleth:1.0:nameIdentifier</md:NameIDFormat>
      <md:NameIDFormat>
urn:oasis:names:tc:SAML:2.0:nameid-format:transient
</md:NameIDFormat>
```

**Comment by leifj** [comment]
I found this: http://stackoverflow.com/questions/33826104/can-xsd-type-of-anyuri-contain-spaces which seems to argue that since anyURI has whitespace="collapse" the consumer should remove that leading and trailing whitespace, so yes it seems to be schema-legal

**Comment by leifj** [comment]
Also cf section 1.3.2 of saml-core-2.0: 

> Unless otherwise indicated in this specification, all URI reference values used within SAML-defined
> elements or attributes MUST consist of at least one non-whitespace character, and are REQUIRED 
> to be absolute [RFC 2396].

This, however doesn't say that whitespace="collapse" doesn't apply.

**Comment by leifj** [comment]
An empty element is of course not valid.

**Comment by leifj** [comment]
I believe #79 is the right way to deal with this.
