### ISSUE TITLE
strip signatures when loading xml from a directory or local file

### ISSUE THREAD

**Issue by leifj** [leifj/pyFF#88]
related to #86 

signature stripping should be done even if validation isn't done probably - at least this should be configurable or available as a pipe

**Comment by leifj** [comment]
Implemented using a pipe "prune" that can strip arbitrary elements based on xpath expressions.

**Comment by leifj** [comment]
Add this to your pipeline:

.. code-block:: yaml
- prune:
     - .//{http://www.w3.org/2000/09/xmldsig#}Signature

**Comment by rhoerbe** [comment]
Will try
