### ISSUE TITLE
Broken metadata modal when clicking summary or contacts

### ISSUE THREAD

**Issue by mkrogh** [leifj/pyFF#94]
When looking at a matadata detail page e.g. http://nightly.pyff.io/metadata/%7Bsha1%7D74a9205aa16eac18dd95f81828b9ad8f73ca0515.html 

If you click on summary or contacts before cliking on the Metadata link you will get an empty modal that you cannot close.

Reproduced in Opra, Chrome and Firefox on OSX.

Furthermore it seems like the detail pages has a script error: `ReferenceError: $ is not defined` that is probably related, jQuery missing?

![Firefox example](https://www.dropbox.com/s/4js562u1de7m2um/Screenshot%202016-07-01%2014.03.09.png?dl=1)

Image of the script error:

![Script error](https://www.dropbox.com/s/ik4vrdde0rgddb0/Screenshot%202016-07-01%2014.06.16.png?dl=1)

**Comment by mkrogh** [comment]
Ahh yes there is also a warning from google maps api about no api keys.

![Google maps api warning](https://www.dropbox.com/s/4apbijx28bvkgjc/Screenshot%202016-07-01%2014.09.50.png?dl=1)

**Comment by leifj** [comment]
resolved by pyFF#272c11dec46c2372d15faf011a5a82d3b7e33c88
