### ISSUE TITLE
Discovery search doesn't work, {http://pyff.io/role} breaks it

### ISSUE THREAD

**Issue by sitya** [leifj/pyFF#96]
E.g.: `http://mdx.eduid.hu/role/%7Bhttp://pyff.io/role%7Didp.s?query=niif&entity_filter={http://macedir.org/entity-category}http://pyff.io/category/discoverable&related=niif.hu` gives empty result, but without `%7Bhttp://pyff.io/role%7D` before `idp.s` it works. This is hardcoded to data-targets, as I saw, so I don't have any idea how to fix it by config :(

I think the pipes and the configuration can be read on the page, I would really appreciate any help, we use it in production, so it really needs to be work.

It runs in Docker, using `leifj/pyff` image.

thanks. 
Tamas

**Comment by sitya** [comment]
I had to make a workaround, I replaced `{{ search }}`  in  `ds.html` to `idp.s`, but it is a temporary solution, so I would be happy to solve this not just work around. Thanks.

**Comment by leifj** [comment]
Skickat från min iPhone

> 1 aug. 2016 kl. 21:34 skrev Frank Tamás <notifications@github.com>:
> 
> E.g.: http://mdx.eduid.hu/role/%7Bhttp://pyff.io/role%7Didp.s?query=niif&entity_filter={http://macedir.org/entity-category}http://pyff.io/category/discoverable&related=niif.hu gives empty result, but without %7Bhttp://pyff.io/role%7D before idp.s it works. This is hardcoded to data-targets, as I saw, so I don't have any idea how to fix it by config :(
> 
> I think the pipes and the configuration can be read on the page, I would really appreciate any help, we use it in production, so it really needs to be work.
> 
> It runs in Docker, using leifj/pyff image.
> 

When did you pull that docker image? Make sure you update as the image was pretty old until late last week.

**Comment by sitya** [comment]
On Tue, Aug 2, 2016 at 7:10 AM, Leif Johansson <notifications@github.com>
wrote:

>
>
> Skickat från min iPhone
>
> > 1 aug. 2016 kl. 21:34 skrev Frank Tamás <notifications@github.com>:
> >
> > E.g.:
> http://mdx.eduid.hu/role/%7Bhttp://pyff.io/role%7Didp.s?query=niif&entity_filter={http://macedir.org/entity-category}http://pyff.io/category/discoverable&related=niif.hu
> <http://mdx.eduid.hu/role/%7Bhttp://pyff.io/role%7Didp.s?query=niif&entity_filter=%7Bhttp://macedir.org/entity-category%7Dhttp://pyff.io/category/discoverable&related=niif.hu>
> gives empty result, but without %7Bhttp://pyff.io/role%7D before idp.s it
> works. This is hardcoded to data-targets, as I saw, so I don't have any
> idea how to fix it by config :(
> >
> > I think the pipes and the configuration can be read on the page, I would
> really appreciate any help, we use it in production, so it really needs to
> be work.
> >
> > It runs in Docker, using leifj/pyff image.
>
> When did you pull that docker image? Make sure you update as the image was
> pretty old until late last week.
>

I pulled it yesterday.

Tamas

**Comment by sitya** [comment]
Just to follow up. Right now I made a clean deploy, without any modification, but the result is the same, I cannot search for any IdP, the json array is always empty.

```shell
➜  ~ docker pull leifj/pyff
Using default tag: latest
latest: Pulling from leifj/pyff

d634beec75db: Pull complete
9c0396af89e3: Pull complete
...
e137c60455fa: Pull complete
4fe5a4065398: Pull complete
Digest: sha256:adbb7106b17f5af0079789ce3ee52bb33ba4e7b4879234b5da75c842ffeddd58
Status: Downloaded newer image for leifj/pyff:latest
➜  ~ docker run -p 8080:8080 leifj/pyff
```

Gives empty list:
`http://192.168.99.100:8080/role/%7Bhttp://pyff.io/role%7Didp.s?query=&entity_filter={http://macedir.org/entity-category}http://pyff.io/category/discoverable&related=niif.hu`

Works fine (without `%7Bhttp://pyff.io/role%7D`):
`http://192.168.99.100:8080/role/idp.s?query=&entity_filter={http://macedir.org/entity-category}http://pyff.io/category/discoverable&related=niif.hu`

I found that the value of `{{ search }}` in `ds.html` comes from `mdx.py` using `kwargs['pfx']`, but I am wondering whether `pfx` is configurable as a workaround, or it is a bug? :)

**Comment by leifj** [comment]
Exactly which url are you using as your DS?

**Comment by leifj** [comment]
Just to clarify: I just tested http://mdx.eduid.hu/role/idp.ds which seems to work as expected (eg http://mdx.eduid.hu/role/idp.ds?entityID=https://sp.swamid.se/shibboleth&return=# renders a DS UI). Which DS URI are you using?

**Comment by sitya** [comment]
I made the [workaround](https://github.com/leifj/pyFF/issues/96#issuecomment-236708051) at mdx.eduid.hu because we use it in production, and it must work. You can try it at entities.eduid.hu This uses the same image and almost the same configuration.

And if you try to make a clean deploy as I wrote above, the problem can be reproduced. For example try to search at: http://[your-local-docker-ip]:8080/role/idp.ds?entityID=https://aai-logon.switch.ch/idp/shibboleth&return=#

**Comment by leifj** [comment]
http://entities.eduid.hu/role/idp.ds?entityID=https://sp.swamid.se/shibboleth&return=# seems to work aswell

**Comment by leifj** [comment]
actually scratch that - I can see it doesn't work

**Comment by leifj** [comment]
I suspect the extra / at the end of the base URL - i.e /search/ vs /search etc. What is your proxy situation? I run exactly the same setup at md.nordu.net behind varnish+pound but you have to tell pound to handle the URL the right way or it doesn't work

**Comment by sitya** [comment]
At entities.eduid.hu do you get list after searching for IdPs? For example if you come from http://earc.eduid.hu (Start test --> goes to entites.eduid.hu), in an incoginto mode browser do you find your IdP? It is really strange, because today it worked for nobody, and it doesn't work for me right now. If I see the console at the browser, I can see the given empty list for the result of the called url: http://entities.eduid.hu/role/%7Bhttp://pyff.io/role%7Didp.s?query=&entity_filter={http://macedir.org/entity-category}http://pyff.io/category/discoverable&related=aai.niif.hu;niif.hu It is empty. For you not? And if I leave `%7Bhttp://pyff.io/role%7D` it will work.

**Comment by leifj** [comment]
It works if you manually remove the / after the search/ in the javascript. Use chrome and open a js console. You should see a bunch of 404s from the search API. Those are due to the extra / at the end of search/ (should be "search" not "search/"). Is there a proxy before pyFF at entities.eduid.hu?

**Comment by sitya** [comment]
Sorry, where should I find this "`search`"? At javascript consol I can see called urls like I wrote earlier: http://entities.eduid.hu/role/%7Bhttp://pyff.io/role%7Didp.s?query=&entity_filter={http://macedir.org/entity-category}http://pyff.io/category/discoverable&related=aai.niif.hu;niif.hu I did not get any 404, just empty results.

On my desktop there is no proxy, I connect to directly: http://192.168.99.100:8080 with the same error, at entites.eduid.hu there is nginx proxy (it is controlled by Deis PaaS).

**Comment by leifj** [comment]
Looking at the JS console output from entities.eduid.hu & comparing it with md.nordu.net, I'm pretty sure it is not in fact running the latest docker image. Can you verify that the docker image you are running is 9482db2952bb ?

**Comment by sitya** [comment]
I pulled again, it is the very latest :) built on docker hub approx 15 minutes ago. I tested it on my desktop, and it works fine. Thank you!

```shell
➜  ~ docker pull leifj/pyff
Using default tag: latest
latest: Pulling from leifj/pyff
Digest: sha256:1ddae7e4c0f182439eafd15e2d291798e9686bfc58dbc036f0392c9fdb20f50a
Status: Image is up to date for leifj/pyff:latest
```

**Comment by sitya** [comment]
Fine, after upgrade docker image it works on mdx and entites.eduid.hu as well. Thanks again.
