### ISSUE TITLE
pyffd/ disco GUI: Real IDP not shown

### ISSUE THREAD

**Issue by rhoerbe** [leifj/pyFF#97]
When making the IDP-selection permanent, a URL appears below:
"If you change your mind, visit http://pyffTestWpv:8080/reset to change your settings."

If operated behind a reverse proxy, the message does not show the reald FQDN from a user perspective.

**Comment by rhoerbe** [comment]
The title should read "Real Discovery Service URL not shown"

**Comment by leifj** [comment]
I have pyFF instances running behind loadbalancers and as long as you use the "standard" X-Forwarded headers those URLs are rendered correctly.

**Comment by rhoerbe** [comment]
Hmm, I have to look into it. My nginx server does have x-forwarded headers set.

**Comment by leifj** [comment]
you can look at md.nordu.net to convince yourself it is possible :-) that one is pound->varnish->pyFF so even more complex than your setup probably
